name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: pytest
      id: pytest
      uses: education/autograding-python-grader@v1
      with:
        timeout: 1
        max-score: 1
        setup-command: ''
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        PYTEST_RESULTS: "${{steps.pytest.outputs.result}}"
      with:
        runners: pytest
